[package]
name = "socks5-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1"
async-trait = "0.1"
socks5-proto = { path = "../socks5-proto" }
tokio = { version = "1.18", features = ["net"] }

[dev-dependencies]
tokio = { version = "1.18", features = ["macros", "rt-multi-thread"] }
